# Generated by Django 3.0.8 on 2020-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200728_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('skillpercentage', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
